### ISSUE TITLE
I get connection refused no matter what I do in the configs

### ISSUE THREAD

**Issue by KennethLavrsen** [shawly/api-scapegoat#10]
I have tried to setup this little addon

I have one simple config

```
---
# the path under which API scapegoat should listen
route: /api
# the api you want to proxy
target: 'http://192.168.1.9'
pathRewrite:
  # all requests to /api/hello will be forwarded to /rest/api/hello
  ^/api: /api
# rewrites the origin of the 'host' header to the target URL
changeOrigin: 'false'
failover:
  response:
    status_code: 202
    headers:
      content-type: application/json
      server: API Scapegoat
    body: '{ "status": "api offline" }'
```

I cannot get any rest sensors in HA to work. And when I try from a termimal inside HA doing a wget request to the URL I get connection refused. Always connection refused.

The addon log is set to debug.

It shows the correct init. There are zero entried after that. It is clear the requests never even reach the nginx server in the addon.

Has it been tested that this addon actually works as of HA 2024.1.2? It seems like all request except for ingress is blocked.
